name: Label & comment issues # The name of the workflow
on: 
  issues:
    types:
      - reopened
      - opened
      - closed
  pull_request:
    types:
      - opened

jobs: 
  label_issues: # Job for labeling and commenting on issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: attach label to issues
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["issue", "fix"]
            })
      - name: Comment on new issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this issue! We'll take a look as soon as possible.

  issue_closed: # Job for commenting on closed issues
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on closed issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 The issue is now resolved!'
            })

  first_pull_request: # Job for congratulating on the first pull request
    if: github.event.pull_request.number == 1
    runs-on: ubuntu-latest
    steps:
      - name: Congratulate on first pull request
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: github.event.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎉 Congratulations on opening your first pull request! We appreciate your contribution.'
            })