# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Lab4practice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://andyaz.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_55332d0f6a9f4069b21455939bffc461 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e43218cf63bc4d4b95240cfd9c56a087 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: andyaz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_55332d0f6a9f4069b21455939bffc461 }}/webapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Lab4practice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d69b81e2c7ce4f409097a27a8a1d0442 }}
        images: 'andyaz.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_55332d0f6a9f4069b21455939bffc461 }}/webapp:${{ github.sha }}'